- name: default value
  hosts: localhost
  tasks:
  - name: print default value
    ansible.builtin.debug:
      msg: "Hello {{course | default('Ansible') }}"


- name: default name
  hosts: localhost
  tasks:
  - name: print some value
    ansible.builtin.debug:
      msg: "Hi Hello"